#!/usr/bin/env bash
# Show the status of compression jobs running in tmux.
#
# Sessions: c<N> (movie), series<N> (series), a<N> (audio).
#
# New jobs write work/<session>.state and ffmpeg -progress output to
# work/<session>.progress. Jobs generated by older versions of the
# scripts have neither; for those the tmux pane history and the job
# script are parsed instead.
set -u

WORK="$HOME/compress/work"
RECENT_HOURS=72

command -v tmux >/dev/null || {
    echo "tmux not found"
    exit 1
}

command -v ffprobe >/dev/null || {
    echo "ffprobe not found"
    exit 1
}

source "$WORK/lib/bitrate.sh"
source "$WORK/lib/media_probe.sh"
source "$WORK/lib/media_stats.sh"

job_type_for() {
    case "$1" in
        c[0-9]*)      echo "movie" ;;
        series[0-9]*) echo "series" ;;
        a[0-9]*)      echo "audio" ;;
        *)            echo "" ;;
    esac
}

# read_state FILE  ->  fills associative array ST
read_state() {
    local k v

    ST=()

    while IFS='=' read -r k v; do
        [[ -n "$k" ]] && ST["$k"]="$v"
    done < "$1"
}

# progress_values FILE  ->  "out_seconds speed progress"
progress_values() {
    tail -n 60 "$1" 2>/dev/null |
    awk -F'=' '
        $1 == "out_time_us" && $2 ~ /^[0-9]+$/ { t = $2 / 1000000 }
        $1 == "out_time_ms" && $2 ~ /^[0-9]+$/ && t == "" { t = $2 / 1000000 }
        $1 == "speed"    { s = $2; sub(/x$/, "", s); gsub(/ /, "", s) }
        $1 == "progress" { p = $2 }
        END {
            printf "%s %s %s\n",
                (t == "" ? "-" : sprintf("%.0f", t)),
                (s ~ /^[0-9.]+$/ ? s : "-"),
                (p == "" ? "-" : p)
        }'
}

# Unquote the first shell word of a line produced by printf %q.
first_word() {
    xargs -n 1 2>/dev/null <<< "$1" | head -n 1
}

# Paths passed to "ffmpeg -y -i" in an (old) job script, in order, unique.
script_inputs() {
    local line

    grep -E '^ *ffmpeg -y -i ' "$1" 2>/dev/null |
    while IFS= read -r line; do
        line="${line#*ffmpeg -y -i }"
        first_word "$line"
    done |
    awk '!seen[$0]++'
}

# step_text PASS [MODE] [CRF]  ->  what the item is doing:
#   "Pass: 1/2" / "Pass: 2/2"      two-pass encode (Quality)
#   "Encoding, CRF: 21"            single-pass CRF encode (no passes)
#   "Step: mux" / "Step: verify"   other steps
step_text() {
    local pass="$1" mode="${2:-}" crf="${3:-}"

    if [[ "$pass" == "encode" ]]; then
        printf 'Encoding%s' "${crf:+, CRF: $crf}"
    elif [[ -z "$pass" || "$pass" == "-" || "$pass" == */* ]]; then
        printf 'Pass: %s' "${pass:--}"
    else
        printf 'Step: %s' "$pass"
    fi
}

print_row() {
    # session type item status name tier step percent encoded total speed eta wall
    local session="$1" type="$2" item="$3" status="$4" name="$5" tier="$6"
    local step="$7" pct="$8" enc="$9" total="${10}" speed="${11}" eta="${12}" wall="${13}"

    printf '%-9s %-7s %-6s %s\n' "$session" "$type" "$item" "$status"
    printf '    %s\n' "$name"

    if [[ "$pct" == "-" ]]; then
        printf '    Tier: %-9s %-11s Elapsed: %s\n' "$tier" "$step" "$wall"
    else
        printf '    Tier: %-9s %-11s %6s   %s / %s   %sx   ETA %s   Elapsed: %s\n' \
            "$tier" "$step" "$pct" "$enc" "$total" "$speed" "$eta" "$wall"
    fi

    echo
}

# progress_fields CURRENT_SEC DURATION SPEED  ->  "percent eta"
progress_fields() {
    awk -v c="$1" -v t="$2" -v s="$3" 'BEGIN {
        if (c !~ /^[0-9.]+$/ || t !~ /^[0-9.]+$/ || t <= 0) { print "- -"; exit }
        pct = c / t * 100
        if (pct > 100) pct = 100
        if (s ~ /^[0-9.]+$/ && s > 0) {
            r = (t - c) / s
            if (r < 0) r = 0
            printf "%.1f%% %.0f\n", pct, r
        } else {
            printf "%.1f%% -\n", pct
        }
    }'
}

declare -A ST
declare -A LIVE
shown=0

mapfile -t sessions < <(
    tmux list-sessions -F '#{session_name} #{session_created}' 2>/dev/null |
    awk '$1 ~ /^(c|series|a)[0-9]+$/' |
    sort -V
)

echo

for entry in "${sessions[@]}"; do
    session="${entry%% *}"
    created="${entry##* }"
    type=$(job_type_for "$session")
    LIVE["$session"]=1

    wall="N/A"
    if [[ "$created" =~ ^[0-9]+$ ]]; then
        wall=$(format_hms "$(( $(date +%s) - created ))")
    fi

    state_file="$WORK/$session.state"
    script="$WORK/$session.sh"

    # --------------------------------------------------------
    # Current job format (state file)
    # --------------------------------------------------------

    if [[ -f "$state_file" ]] &&
       [[ ! -f "$script" || ! "$state_file" -ot "$script" ]]; then

        read_state "$state_file"

        name="${ST[name]:-?}"
        tier="${ST[tier]:-?}"
        item="${ST[item]:-0}/${ST[items]:-?}"
        pass="${ST[pass]:-}"
        duration="${ST[duration]:-}"
        status="${ST[status]:-?}"

        case "$status" in
            failed)
                print_row "$session" "$type" "$item" \
                    "FINISHED WITH ERRORS: ${ST[ok]:-0} ok, ${ST[failed]:-0} failed (session waits for Enter)" \
                    "Logs: ${ST[log_dir]:-?}" "$tier" "$(step_text -)" "-" "" "" "" "" "$wall"
                ((shown++))
                continue
                ;;
            finished)
                print_row "$session" "$type" "$item" \
                    "Finished: ${ST[ok]:-0} ok" "$name" "$tier" "$(step_text -)" "-" "" "" "" "" "$wall"
                ((shown++))
                continue
                ;;
        esac

        read -r cur speed prog <<< "$(progress_values "${ST[progress]:-$WORK/$session.progress}")"

        label="Encoding"
        (( ${ST[failed]:-0} > 0 )) && label="Encoding (${ST[failed]} failed so far)"

        step=$(step_text "$pass" "${ST[mode]:-}" "${ST[crf]:-}")

        if [[ -z "$pass" || "$cur" == "-" ]]; then
            start="Starting"
            if [[ "$pass" == "encode" ]]; then
                start="Starting encode"
            elif [[ -n "$pass" ]]; then
                start="Starting pass $pass"
            fi
            print_row "$session" "$type" "$item" "$start" \
                "$name" "$tier" "$step" "-" "" "" "" "" "$wall"
        else
            read -r pct eta <<< "$(progress_fields "$cur" "$duration" "$speed")"
            print_row "$session" "$type" "$item" "$label" \
                "$name" "$tier" "$step" "$pct" \
                "$(format_hms "$cur")" "$(format_hms "$duration")" \
                "$speed" "$(format_hms "$eta")" "$wall"
        fi

        ((shown++))
        continue
    fi

    # --------------------------------------------------------
    # Legacy jobs: parse pane history + job script
    # --------------------------------------------------------

    pane=$(tmux capture-pane -p -J -S - -t "=$session:" 2>/dev/null || true)

    input=""
    name="Unknown"
    tier=$(grep -oE 'Tier:[[:space:]]*[^"]+' <<< "$pane" | tail -n 1 | sed -E 's/^Tier:[[:space:]]*//')
    pass=$(grep -oE 'PASS [0-9]/[0-9]' <<< "$pane" | tail -n 1 | cut -d' ' -f2)
    item="-"

    case "$type" in
        movie)
            input=$(grep -E '^Encoding: ' <<< "$pane" | tail -n 1 | sed -E 's/^Encoding: //')

            if [[ -f "$script" ]]; then
                mapfile -t all < <(script_inputs "$script")
                for i in "${!all[@]}"; do
                    if [[ "${all[$i]}" == "$input" ]]; then
                        item="$((i + 1))/${#all[@]}"
                    fi
                done
            fi
            ;;
        series)
            item=$(grep -oE 'Episode [0-9]+/[0-9]+' <<< "$pane" | tail -n 1 | cut -d' ' -f2)
            file=$(grep -E '^File: ' <<< "$pane" | tail -n 1 | sed -E 's/^File: //')

            if [[ -n "$file" && -f "$script" ]]; then
                while IFS= read -r p; do
                    if [[ "$(basename "$p")" == "$file" ]]; then
                        input="$p"
                        break
                    fi
                done < <(script_inputs "$script")
            fi

            [[ -z "$input" && -n "$file" ]] && name="$file"
            ;;
        audio)
            if [[ -f "$script" ]]; then
                input=$(first_word "$(grep -m1 -E '^IN=' "$script" | sed -E 's/^IN=//')")
            fi
            pass="mux"
            tier="audio"
            item="1/1"
            ;;
    esac

    [[ -n "$input" ]] && name=$(basename "$input")
    [[ -n "$tier" ]] || tier="?"
    [[ -n "$item" ]] || item="-"

    cur=$(grep -oE 'time=-?[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]+' <<< "$pane" | tail -n 1 | cut -d= -f2)
    speed=$(grep -oE 'speed=[ ]*[0-9.]+x' <<< "$pane" | tail -n 1 | sed -E 's/speed=[ ]*//; s/x$//')

    duration=""
    if [[ -n "$input" && -f "$input" ]]; then
        duration=$(get_duration "$input" 2>/dev/null || true)
    fi

    if [[ -z "$cur" || "$cur" == -* ]]; then
        print_row "$session" "$type" "$item" "Starting (old job format)" \
            "$name" "$tier" "$(step_text "${pass:--}")" "-" "" "" "" "" "$wall"
    else
        IFS=: read -r h m s <<< "$cur"
        cur_sec=$(awk -v h="$h" -v m="$m" -v s="$s" 'BEGIN { printf "%.0f", h*3600 + m*60 + s }')
        read -r pct eta <<< "$(progress_fields "$cur_sec" "$duration" "${speed:--}")"
        print_row "$session" "$type" "$item" "Encoding (old job format)" \
            "$name" "$tier" "$(step_text "${pass:--}")" "$pct" \
            "$(format_hms "$cur_sec")" "$(format_hms "$duration")" \
            "${speed:--}" "$(format_hms "$eta")" "$wall"
    fi

    ((shown++))
done

if (( shown == 0 )); then
    echo "No compression tmux sessions running."
    echo
fi

# ------------------------------------------------------------
# Recently ended jobs (state file left behind, session gone)
# ------------------------------------------------------------

ended=0

while IFS= read -r -d '' state_file; do
    session=$(basename "$state_file" .state)
    [[ -n "${LIVE[$session]+x}" ]] && continue
    [[ -n "$(job_type_for "$session")" ]] || continue

    read_state "$state_file"

    if (( ended == 0 )); then
        echo "Recently ended (last ${RECENT_HOURS}h):"
        echo
    fi
    ((ended++))

    when=$(date -d "@${ST[updated]:-0}" '+%F %H:%M' 2>/dev/null || echo "?")

    case "${ST[status]:-}" in
        finished)    result="finished: ${ST[ok]:-0}/${ST[items]:-?} ok" ;;
        failed)      result="FINISHED WITH ERRORS: ${ST[ok]:-0} ok, ${ST[failed]:-0} failed" ;;
        interrupted) result="INTERRUPTED at item ${ST[item]:-?}/${ST[items]:-?} (${ST[name]:-?})" ;;
        *)           result="STOPPED UNEXPECTEDLY at item ${ST[item]:-?}/${ST[items]:-?} (${ST[name]:-?})" ;;
    esac

    printf '%-9s %-7s %s  %s\n' "$session" "${ST[type]:-?}" "$when" "$result"

    if [[ "${ST[status]:-}" != "finished" && -d "${ST[log_dir]:-/nonexistent}" ]]; then
        printf '    Logs: %s\n' "${ST[log_dir]}"
    fi
done < <(
    find "$WORK" -maxdepth 1 -type f -name '*.state' \
        -mmin "-$((RECENT_HOURS * 60))" -print0 2>/dev/null |
    sort -zV
)

(( ended > 0 )) && echo
exit 0
